services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/
    networks:
      - rede_app
    ports:
      - "1000:80"
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - db_password

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - rede_app
    secrets:
      - db_password
      - db_root

secrets:
  db_root:
    file: secrets/db_root.txt
  db_password:
    file: secrets/db_password.txt

volumes:
  wordpress:
  mysql:

networks:
  rede_app:
    external: true