services:





  grafana:
    image: grafana/grafana:main
    networks:
      - rede_app
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    deploy:
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:main
    networks:
      - rede_app
    ports:
      - '9090:9090'
    volumes:
      - prometheus-storage:/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    deploy:
      restart_policy:
        condition: on-failure

networks:
  rede_app:
    external: true

volumes:
  grafana-storage:
  prometheus-storage:

configs:
  prometheus_config:
    external: true